# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70ba5f607be1e83f588a032ed8a083accbf986a1e04694c47609c043dae232632f88bf8663308ac836f2c0b5a09aab922ba5106b58c55fb19cfe1f22d43b25b

test:
  secret_key_base: efb3ea2a4424fa1e64e053e15c7a0ce462298e8545064e3ec5c492b8816e2dfc92a30d4f0424160e89502db81a6d3eccb46125b25db063b49fb73927c282fc9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
